pipeline {
    agent any
    environment {
        AWS_DEFAULT_REGION = 'us-east-1'
    }
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from project-3...' // Placeholder step
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws-credential', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    bat '''
                    aws --version
                    aws sts get-caller-identity
                    aws s3 ls
                    aws ec2 describe-instances
                    '''
                }
            }
        }
        stage('Build') {
            when {
                branch 'main' // Or some other condition
            }
            steps {
                bat 'echo "Building the project-3..."' // Use bat instead of sh
                bat '''
                aws --version
                aws sts get-caller-identity
                '''
            }
        }
        stage('Test') {
            when {
                branch 'develop' // Or some other condition
            }
            steps {
                bat 'echo "Running tests from project-3..."' // Use bat instead of sh
            }
        }
        stage('Deploy') {
            steps {
                bat 'echo "Deploying the project-3..."' // Use bat instead of sh
            }
        }
    }
}