pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from project-3...' // Placeholder step
            }
        }
        stage('Build') {
            when {
                branch 'main' // Or some other condition
            }
            steps {
                bat 'echo "Building the project-3..."' // Use bat instead of sh
            }
        }
        stage('Test') {
            when {
                branch 'develop' // Or some other condition
            }
            steps {
                bat 'echo "Running tests from project-3..."' // Use bat instead of sh
            }
        }
        stage('Deploy') {
            steps {
                bat 'echo "Deploying the project-3..."' // Use bat instead of sh
            }
        }
    }
}