# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.97.0"
    }

    github = {
      source  = "integrations/github"
      version = " 6.6.0"
    }

    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "2.36.0"
    }

    tls = {
      source  = "hashicorp/tls"
      version = "4.1.0"
    }

  }
  required_version = "1.11.4"
}

provider "aws" {
  region = "eu-west-1"

  # only these aws account ids may be operated on by this template
  allowed_account_ids = ["442042520134"]
}
